version: '3'
services:
  go-app:
    build: .
    ports:
      - "8080:8080"  # Expose the Go app port
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"  # Expose the PostgreSQL port
